export class PermissionHelper {
    static CONFIGURATIONS = "CONFIGURATIONS";

    static USER_CHANGE_PASSWORD_ADMIN = "USER_CHANGE_PASSWORD_ADMIN";
    static USER_VIEW = "USER_VIEW";
    static USER_ADD = "USER_ADD";

    static USER_PROFILE_VIEW = "USER_PROFILE_VIEW";
    static USER_PROFILE_ADD = "USER_PROFILE_ADD";

    static CUSTOMER_VIEW = "CUSTOMER_VIEW";
    static CUSTOMER_ADD = "CUSTOMER_ADD";

    static MENTORED_VIEW = "MENTORED_VIEW";
    static MENTORED_ADD = "MENTORED_ADD";
    static MENTORED_REMOVE = "MENTORED_REMOVE";

    static PARTNER_ADD = "PARTNER_ADD";
    static PARTNER_VIEW = "PARTNER_VIEW";

    static LAUNCH_VIEW = "LAUNCH_VIEW";
    static LAUNCH_ADD = "LAUNCH_ADD";

    static CUSTOMERLAUNCH_VIEW = "CUSTOMERLAUNCH_VIEW";
    static CUSTOMERLAUNCH_ADD = "CUSTOMERLAUNCH_ADD";

    static PRODUCT_VIEW = "PRODUCT_VIEW";
    static PRODUCT_ADD = "PRODUCT_ADD";

    static CUSTOMER_PRODUCT_VIEW = "CUSTOMER_PRODUCT_VIEW";
    static CUSTOMER_PRODUCT_ADD = "CUSTOMER_PRODUCT_ADD";

    static CUSTOMER_AWARD_VIEW = "CUSTOMER_AWARD_VIEW";
    static CUSTOMER_AWARD_ADD = "CUSTOMER_AWARD_ADD";

    static AWARD_VIEW = "AWARD_VIEW";
    static AWARD_ADD = "AWARD_ADD";

    static PAYMENT_METHOD_VIEW = "PAYMENT_METHOD_VIEW";
    static PAYMENT_METHOD_ADD = "PAYMENT_METHOD_ADD";

    static CLASS_VIEW = "CLASS_VIEW";
    static CLASS_ADD = "CLASS_ADD";

    static EXPANSE_CONTROL_VIEW = "EXPANSE_CONTROL_VIEW";
    static EXPANSE_CONTROL_ADD = "EXPANSE_CONTROL_ADD";
    static EXPANSE_CONTROL_REMOVE = "EXPANSE_CONTROL_REMOVE";

    static REPORT_MENTORED = "REPORT_MENTORED";

    static REPORT_INVOICE_VIEW_MENTORED = "REPORT_INVOICE_VIEW_MENTORED";

    static EMPLOYEE_VIEW = "EMPLOYEE_VIEW";
    static EMPLOYEE_ADD = "EMPLOYEE_ADD";

    static PROVIDER_VIEW = "PROVIDER_VIEW";
    static PROVIDER_ADD = "PROVIDER_ADD";

    static EXPENSE_CATEGORY_VIEW = "EXPENSE_CATEGORY_VIEW";
    static EXPENSE_CATEGORY_ADD = "EXPENSE_CATEGORY_ADD";

    static DAILY_PAYMENT_VIEW = "DAILY_PAYMENT_VIEW";
    static DAILY_PAYMENT_ADD = "DAILY_PAYMENT_ADD";
    static DAILY_PAYMENT_REMOVE = "DAILY_PAYMENT_REMOVE";

    static CATEGORY_BENS_VIEW = "CATEGORY_BENS_VIEW";
    static CATEGORY_BENS_ADD = "CATEGORY_BENS_ADD";

    static PATRIMONY_VIEW = "PATRIMONY_VIEW";
    static PATRIMONY_ADD = "PATRIMONY_ADD";

    static PURCHASE_CONTROL_VIEW = "PURCHASE_CONTROL_VIEW";
    static PURCHASE_CONTROL_ADD = "PURCHASE_CONTROL_ADD";

    static PENDENCY_VIEW = "PENDENCY_VIEW";
    static PENDENCY_ADD = "PENDENCY_ADD";

    static SENT_VIEW = "SENT_VIEW";
    static SENT_ADD = "SENT_ADD";

    static APP_VIEW = "APP_VIEW";
    static APP_ADD = "APP_ADD";

    static GIFT_VIEW = "GIFT_VIEW";
    static GIFT_ADD = "GIFT_ADD";
}
